FROM ubuntu
MAINTAINER Sebastian Gebski <sebastian@gebski.net>
LABEL description="Gossip"

# Set the locale, otherwise elixir will complain later on
RUN locale-gen en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8

RUN apt-get update && apt-get upgrade -y
RUN apt-get install -y libsctp-dev libssl-dev inotify-tools

# RUN apk add --no-cache lksctp-tools openssl

RUN apt-get clean -y
RUN apt-get autoclean -y
RUN apt-get autoremove -y