version: '2'
services:
  postgres:
    image: postgres
    environment:
    - POSTGRES_PASSWORD=postgres
    ports:
    - "5432:5432"
  phoenix:
    image: gossip-run
    external_links:
    - gossip_vol
    volumes_from:
    - container:gossip_vol
    # - logs:/var/log
    depends_on:
    - postgres
    links:
    - postgres
    environment:
    - MIX_ENV=prod
    ports:
    - "4000:4000"
    command: gossip/rel/gossip_phx/bin/gossip_phx console
#volumes:
#  logs: {}
#  data: {}
