version: '2'
services:
  postgres:
    image: postgres
    environment:
    - POSTGRES_PASSWORD=postgres
    ports:
    - "5432:5432"
#  web:
#    image: elixir
#    volumes:
#    - ".:/gossip"
#    # - logs:/var/log
#    depends_on:
#    - postgres
#    links:
#    - postgres
#    environment:
#    - MIX_ENV=dev
#    ports:
#    - "4000:4000"
#    command: mix phoenix.server
#volumes:
#  logs: {}
#  data: {}
