FROM elixir
MAINTAINER Sebastian Gebski <sebastian@gebski.net>
LABEL description="Gossip"

# Set the locale, otherwise elixir will complain later on
# RUN locale-gen en_US.UTF-8
# ENV LANG en_US.UTF-8
# ENV LANGUAGE en_US:en
# ENV LC_ALL en_US.UTF-8

# ADD . /gossip
# WORKDIR /gossip

RUN apt-get update && apt-get upgrade -y
RUN apt-get install -y sudo
RUN curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
RUN sudo apt-get install -y nodejs
