version: '2'
services:
  postgres:
    image: postgres
    environment:
    - POSTGRES_PASSWORD=postgres
    volumes:
    - postgres_data:/var/lib/postgresql
    - postgres_logs:/var/log/postgresql
    ports:
    - "5432:5432"
  phoenix_1:
    image: gossip-run
    external_links:
    - gossip_vol
    volumes_from:
    - container:gossip_vol
    # - logs:/var/log
    depends_on:
    - postgres
    links:
    - postgres
    environment:
    - MIX_ENV=prod
    - RELEASE_CONFIG_FILE=/gossip/rel/gossip_phx_1.conf
    ports:
    - "4000:4000"
    command: gossip/rel/gossip_phx/bin/gossip_phx foreground
  phoenix_2:
    image: gossip-run
    external_links:
    - gossip_vol
    volumes_from:
    - container:gossip_vol
    # - logs:/var/log
    depends_on:
    - postgres
    links:
    - postgres
    environment:
    - MIX_ENV=prod
    - RELEASE_CONFIG_FILE=/gossip/rel/gossip_phx_2.conf
    ports:
    - "4001:4001"
    command: gossip/rel/gossip_phx/bin/gossip_phx foreground
  proxy:
    image: gossip-haproxy
    depends_on:
    - phoenix_1
    - phoenix_2
    links:
    - phoenix_1
    - phoenix_2
    ports:
    - "80:80"
volumes:
  postgres_logs:
  postgres_data:
